#region Copyright
//
// All rights are reserved. Reproduction or transmission in whole or in part, in
// any form or by any means, electronic, mechanical or otherwise, is prohibited
// without the prior written consent of the copyright owner.
//
#endregion

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Runtime.InteropServices;
using System.Web.Services;
using System.Web.Services.Description;
using System.Web.Services.Protocols;
using System.Xml.Serialization;
using Avalara.AvaTax.Adapter.AccountService;

//------------------------------------------------------------------------------
// <autogenerated>
//     This code was generated by a tool.
//     Runtime Version: 1.1.4322.2032
//
//     Changes to this file may cause incorrect behavior and will be lost if 
//     the code is regenerated.
// </autogenerated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 1.1.4322.2032.
// 

namespace Avalara.AvaTax.Adapter.Proxies.AccountSvcProxy
{
    /// <include file='AccountSvcProxy.Doc.xml' path='adapter/proxy/AccountSvcProxy/*' />
    [DebuggerStepThrough()]
    [DesignerCategory("code")]
    [WebServiceBinding(Name = "AccountSvcSoap", Namespace = "http://avatax.avalara.com/services")]
    [XmlInclude(typeof(ProxyBaseResult))]
    [ComVisible(false)]
    public class ProxyAccountSvc : SoapHttpClientProtocol
    {
        /// <remarks/>
        public ProxyProfile ProfileValue;
        /// <remarks/>
        public ProxySecurity Security;

        /// <remarks/>
        internal ProxyAccountSvc()
        {
            //not publicly creatable
        }

        /// <remarks/>
        [SOAPTraceRequest]
        [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/Ping", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyPingResult Ping(string Message)
        {
            object[] results = this.Invoke("Ping", new object[] {
                        Message});
            return ((ProxyPingResult)(results[0]));
        }

        /// <remarks/>
        //public void PingAsync(string Message)
        //{
        //    this.PingAsync(Message, null);
        //}

        ///// <remarks/>
        //public void PingAsync(string Message, object userState)
        //{
        //    if ((this.PingOperationCompleted == null))
        //    {
        //        this.PingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPingOperationCompleted);
        //    }
        //    this.InvokeAsync("Ping", new object[] {
        //                Message}, this.PingOperationCompleted, userState);
        //}

        ////private void OnPingOperationCompleted(object arg)
        //{
        //    if ((this.PingCompleted != null))
        //    {
        //        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        //        this.PingCompleted(this, new PingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        //    }
        //}

        //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
        //[System.Diagnostics.DebuggerStepThroughAttribute()]
        //[System.ComponentModel.DesignerCategoryAttribute("code")]
        //public class PingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        //{

        //    private object[] results;

        //    internal PingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        //        base(exception, cancelled, userState)
        //    {
        //        this.results = results;
        //    }

        //    /// <remarks/>
        //    public PingResult Result
        //    {
        //        get
        //        {
        //            this.RaiseExceptionIfNecessary();
        //            return ((PingResult)(this.results[0]));
        //        }
        //    }
        //}

        //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
        //public delegate void PingCompletedEventHandler(object sender, PingCompletedEventArgs e);

        //public event PingCompletedEventHandler PingCompleted;

        //private System.Threading.SendOrPostCallback PingOperationCompleted;
        /// <remarks/>
        [SOAPTraceRequest]
        [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/IsAuthorized", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyIsAuthorizedResult IsAuthorized(string Operations)
        {
            object[] results = this.Invoke("IsAuthorized", new object[] {
                        Operations});
            return ((ProxyIsAuthorizedResult)(results[0]));
        }

        /// <remarks/>
        [SOAPTraceRequest]
        [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/CompanyFetch", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyCompanyFetchResult CompanyFetch(ProxyFetchRequest FetchRequest)
        {
            try
            {
                object[] results = this.Invoke("CompanyFetch", new object[] {
                        FetchRequest});
                return ((ProxyCompanyFetchResult)(results[0]));
            }
            catch (Exception)
            {
                throw;
            }
        }

        ///// <remarks/>
        //public void CompanyFetchAsync(ProxyFetchRequest FetchRequest)
        //{
        //    this.CompanyFetchAsync(FetchRequest, null);
        //}

        ///// <remarks/>
        //public void CompanyFetchAsync(ProxyFetchRequest FetchRequest, object userState)
        //{
        //    if ((this.CompanyFetchOperationCompleted == null))
        //    {
        //        this.CompanyFetchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCompanyFetchOperationCompleted);
        //    }
        //    this.InvokeAsync("CompanyFetch", new object[] {
        //                FetchRequest}, this.CompanyFetchOperationCompleted, userState);
        //}


        //private void OnCompanyFetchOperationCompleted(object arg)
        //{
        //    if ((this.CompanyFetchCompleted != null))
        //    {
        //        System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
        //        this.CompanyFetchCompleted(this, new ProxyCompanyFetchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        //    }
        //}

        //private System.Threading.SendOrPostCallback CompanyFetchOperationCompleted;
        ///// <remarks/>
        //public event CompanyFetchCompletedEventHandler CompanyFetchCompleted;

        ///// <remarks/>
        //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
        //public delegate void CompanyFetchCompletedEventHandler(object sender, ProxyCompanyFetchCompletedEventArgs e);

        ///// <remarks/>
        //[System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.34209")]
        //[System.Diagnostics.DebuggerStepThroughAttribute()]
        //[System.ComponentModel.DesignerCategoryAttribute("code")]
        //public  class ProxyCompanyFetchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
        //{

        //    private object[] results;

        //    internal ProxyCompanyFetchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
        //        base(exception, cancelled, userState)
        //    {
        //        this.results = results;
        //    }

        //    /// <remarks/>
        //    public ProxyCompanyFetchResult Result
        //    {
        //        get
        //        {
        //            this.RaiseExceptionIfNecessary();
        //            return ((ProxyCompanyFetchResult)(this.results[0]));
        //        }
        //    }
        //}

        /// <remarks/>
        [SOAPTraceRequest]
        [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/NexusFetch", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyNexusFetchResult NexusFetch(ProxyFetchRequest FetchRequest)
        {
            object[] results = this.Invoke("NexusFetch", new object[] {
                        FetchRequest});
            return ((ProxyNexusFetchResult)(results[0]));
        }

        /// <remarks/>
        [SOAPTraceRequest]
        [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/CompanySave", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyCompanySaveResult CompanySave(ProxyCompany Company)
        {
            object[] results = this.Invoke("CompanySave", new object[] {
                    Company});
            return ((ProxyCompanySaveResult)(results[0]));
        }

        /// <remarks/>
         [SOAPTraceRequest]
         [SoapHeader("ProfileValue"), SoapHeader("Security")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/NexusSave", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public ProxyNexusSaveResult NexusSave(ProxyNexus Nexus)
        {
            object[] results = this.Invoke("NexusSave", new object[] {
                    Nexus});
            return ((ProxyNexusSaveResult)(results[0]));
        }

         /// <remarks/>
         [SOAPTraceRequest]
         [SoapHeader("ProfileValue"), SoapHeader("Security")]
         [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/UserFetch", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
         public ProxyUserFetchResult UserFetch(ProxyFetchRequest FetchRequest)
         {
             object[] results = this.Invoke("UserFetch", new object[] {
                        FetchRequest});
             return ((ProxyUserFetchResult)(results[0]));
         }

         /// <remarks/>
         [SOAPTraceRequest]
         [SoapHeader("ProfileValue"), SoapHeader("Security")]
         [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://avatax.avalara.com/services/UserSave", RequestNamespace = "http://avatax.avalara.com/services", ResponseNamespace = "http://avatax.avalara.com/services", Use = System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle = System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
         public ProxyUserSaveResult UserSave(ProxyUser User)
         {
             object[] results = this.Invoke("UserSave", new object[] {
                        User});
             return ((ProxyUserSaveResult)(results[0]));
         }

    }
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "UserSaveResult")]
    public class ProxyUserSaveResult : ProxyBaseResult
    {
        private int userIdField;

        /// <remarks/>
        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }
                
    }
    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "NexusSaveResult")]
    [ComVisible(false)]
    public partial class ProxyNexusSaveResult : ProxyBaseResult
    {

        private int nexusIdField;

        /// <remarks/>
        public int NexusId
        {
            get
            {
                return this.nexusIdField;
            }
            set
            {
                this.nexusIdField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanySaveResult")]
    [ComVisible(false)]
    public class ProxyCompanySaveResult : ProxyBaseResult
    {
        private int companyIdField;

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "FetchRequest")]
    [ComVisible(false)]
    public class ProxyFetchRequest : ProxyBaseRequest
    {

        private string fieldsField;

        private string filtersField;

        private string sortField;

        private int maxCountField;

        private int pageIndexField;

        private int pageSizeField;

        private int recordCountField;

        /// <remarks/>
        public string Fields
        {
            get
            {
                return this.fieldsField;
            }
            set
            {
                this.fieldsField = value;
            }
        }

        /// <remarks/>
        public string Filters
        {
            get
            {
                return this.filtersField;
            }
            set
            {
                this.filtersField = value;
            }
        }

        /// <remarks/>
        public string Sort
        {
            get
            {
                return this.sortField;
            }
            set
            {
                this.sortField = value;
            }
        }

        /// <remarks/>
        public int MaxCount
        {
            get
            {
                return this.maxCountField;
            }
            set
            {
                this.maxCountField = value;
            }
        }

        /// <remarks/>
        public int PageIndex
        {
            get
            {
                return this.pageIndexField;
            }
            set
            {
                this.pageIndexField = value;
            }
        }

        /// <remarks/>
        public int PageSize
        {
            get
            {
                return this.pageSizeField;
            }
            set
            {
                this.pageSizeField = value;
            }
        }

        /// <remarks/>
        public int RecordCount
        {
            get
            {
                return this.recordCountField;
            }
            set
            {
                this.recordCountField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanyFetchResult")]
    [ComVisible(false)]
    public class ProxyCompanyFetchResult : ProxyBaseResult
    {
        /// <remarks/>
        public ProxyCompany[] Companies;
        
        /// <remarks/>
        public int RecordCount;
       
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "Company")]
    [ComVisible(false)]
    public class ProxyCompany
    {
        private int accountIdField;

        private int companyIdField;

        private string companyCodeField;

        private string companyNameField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private int entityNoField;

        private bool hasProfileField;

        private bool isActiveField;

        private bool isDefaultField;

        private bool isReportingEntityField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private int parentIdField;

        private System.DateTime sSTEffDateField;

        private string sSTPIDField;

        private string tINField;

        private string regalBankIdField;

        private string defaultCountryField;

        private string baseCurrencyCodeField;

        private RoundingLevelId roundingLevelIdField;

        private bool cashBasisAccountingEnabledField;

        private ProxyCompany[] childrenField;

        private ProxyCompanyContact[] contactsField;

        private ProxyItem[] itemsField;

        private ProxyNexus[] nexusesField;

        private ProxyCompany parentField;

        private ProxyTaxCode[] taxCodesField;

        private ProxyTaxRule[] taxRulesField;

        private ProxyCompanyReturn[] filingCalendarsField;

        private bool warningsEnabledField;

        private bool isTestField;

        private TaxDependencyLevelId taxDependencyLevelIdField;

        private bool inProgressField;

        private int defaultLocationIdField;

        private string businessIdentificationNoField;

        /// <remarks/>
        public int AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string CompanyCode
        {
            get
            {
                return this.companyCodeField;
            }
            set
            {
                this.companyCodeField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public int EntityNo
        {
            get
            {
                return this.entityNoField;
            }
            set
            {
                this.entityNoField = value;
            }
        }

        /// <remarks/>
        public bool HasProfile
        {
            get
            {
                return this.hasProfileField;
            }
            set
            {
                this.hasProfileField = value;
            }
        }

        /// <remarks/>
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        public bool IsDefault
        {
            get
            {
                return this.isDefaultField;
            }
            set
            {
                this.isDefaultField = value;
            }
        }

        /// <remarks/>
        public bool IsReportingEntity
        {
            get
            {
                return this.isReportingEntityField;
            }
            set
            {
                this.isReportingEntityField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public int ParentId
        {
            get
            {
                return this.parentIdField;
            }
            set
            {
                this.parentIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime SSTEffDate
        {
            get
            {
                return this.sSTEffDateField;
            }
            set
            {
                this.sSTEffDateField = value;
            }
        }

        /// <remarks/>
        public string SSTPID
        {
            get
            {
                return this.sSTPIDField;
            }
            set
            {
                this.sSTPIDField = value;
            }
        }

        /// <remarks/>
        public string TIN
        {
            get
            {
                return this.tINField;
            }
            set
            {
                this.tINField = value;
            }
        }

        /// <remarks/>
        public string RegalBankId
        {
            get
            {
                return this.regalBankIdField;
            }
            set
            {
                this.regalBankIdField = value;
            }
        }

        /// <remarks/>
        public string DefaultCountry
        {
            get
            {
                return this.defaultCountryField;
            }
            set
            {
                this.defaultCountryField = value;
            }
        }

        /// <remarks/>
        public string BaseCurrencyCode
        {
            get
            {
                return this.baseCurrencyCodeField;
            }
            set
            {
                this.baseCurrencyCodeField = value;
            }
        }

        /// <remarks/>
        public RoundingLevelId RoundingLevelId
        {
            get
            {
                return this.roundingLevelIdField;
            }
            set
            {
                this.roundingLevelIdField = value;
            }
        }

        /// <remarks/>
        public bool CashBasisAccountingEnabled
        {
            get
            {
                return this.cashBasisAccountingEnabledField;
            }
            set
            {
                this.cashBasisAccountingEnabledField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany[] Children
        {
            get
            {
                return this.childrenField;
            }
            set
            {
                this.childrenField = value;
            }
        }

        /// <remarks/>
        public ProxyCompanyContact[] Contacts
        {
            get
            {
                return this.contactsField;
            }
            set
            {
                this.contactsField = value;
            }
        }

        /// <remarks/>
        public ProxyItem[] Items
        {
            get
            {
                return this.itemsField;
            }
            set
            {
                this.itemsField = value;
            }
        }

        /// <remarks/>
        public ProxyNexus[] Nexuses
        {
            get
            {
                return this.nexusesField;
            }
            set
            {
                this.nexusesField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany Parent
        {
            get
            {
                return this.parentField;
            }
            set
            {
                this.parentField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxCode[] TaxCodes
        {
            get
            {
                return this.taxCodesField;
            }
            set
            {
                this.taxCodesField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxRule[] TaxRules
        {
            get
            {
                return this.taxRulesField;
            }
            set
            {
                this.taxRulesField = value;
            }
        }

        /// <remarks/>
        public ProxyCompanyReturn[] FilingCalendars
        {
            get
            {
                return this.filingCalendarsField;
            }
            set
            {
                this.filingCalendarsField = value;
            }
        }

        /// <remarks/>
        public bool WarningsEnabled
        {
            get
            {
                return this.warningsEnabledField;
            }
            set
            {
                this.warningsEnabledField = value;
            }
        }

        /// <remarks/>
        public bool IsTest
        {
            get
            {
                return this.isTestField;
            }
            set
            {
                this.isTestField = value;
            }
        }

        /// <remarks/>
        public TaxDependencyLevelId TaxDependencyLevelId
        {
            get
            {
                return this.taxDependencyLevelIdField;
            }
            set
            {
                this.taxDependencyLevelIdField = value;
            }
        }

        /// <remarks/>
        public bool InProgress
        {
            get
            {
                return this.inProgressField;
            }
            set
            {
                this.inProgressField = value;
            }
        }

        /// <remarks/>
        public int DefaultLocationId
        {
            get
            {
                return this.defaultLocationIdField;
            }
            set
            {
                this.defaultLocationIdField = value;
            }
        }

        /// <remarks/>
        public string BusinessIdentificationNo
        {
            get
            {
                return this.businessIdentificationNoField;
            }
            set
            {
                this.businessIdentificationNoField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "RoundingLevelId")]
    [ComVisible(false)]
    public enum RoundingLevelId
    {

        /// <remarks/>
        Line,

        /// <remarks/>
        Document,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanyContact")]
    [ComVisible(false)]
    public class ProxyCompanyContact
    {

        private string cityField;

        private int companyIdField;

        private string companyContactCodeField;

        private int companyContactIdField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private string emailField;

        private string faxField;

        private string firstNameField;

        private string lastNameField;

        private string countryField;

        private string line1Field;

        private string line2Field;

        private string line3Field;

        private string middleNameField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private string phoneField;

        private string phone2Field;

        private string postalCodeField;

        private string regionField;

        private string titleField;

        private ProxyCompany companyField;

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string CompanyContactCode
        {
            get
            {
                return this.companyContactCodeField;
            }
            set
            {
                this.companyContactCodeField = value;
            }
        }

        /// <remarks/>
        public int CompanyContactId
        {
            get
            {
                return this.companyContactIdField;
            }
            set
            {
                this.companyContactIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string Fax
        {
            get
            {
                return this.faxField;
            }
            set
            {
                this.faxField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        /// <remarks/>
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        /// <remarks/>
        public string Line3
        {
            get
            {
                return this.line3Field;
            }
            set
            {
                this.line3Field = value;
            }
        }

        /// <remarks/>
        public string MiddleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string Phone2
        {
            get
            {
                return this.phone2Field;
            }
            set
            {
                this.phone2Field = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string Title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany ProxyCompany
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "Item")]
    [ComVisible(false)]
    public class ProxyItem
    {

        private long itemIdField;

        private string itemCodeField;

        private int companyIdField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private int taxCodeIdField;

        private string descriptionField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private ProxyCompany companyField;

        private ProxyTaxCode taxCodeField;

        /// <remarks/>
        public long ItemId
        {
            get
            {
                return this.itemIdField;
            }
            set
            {
                this.itemIdField = value;
            }
        }

        /// <remarks/>
        public string ItemCode
        {
            get
            {
                return this.itemCodeField;
            }
            set
            {
                this.itemCodeField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public int TaxCodeId
        {
            get
            {
                return this.taxCodeIdField;
            }
            set
            {
                this.taxCodeIdField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany ProxyCompany
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxCode TaxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TaxCode")]
    [ComVisible(false)]
    public class ProxyTaxCode
    {

        private int taxCodeIdField;

        private string taxCodeValueField;

        private string taxCodeTypeIdField;

        private int companyIdField;

        private string descriptionField;

        private bool isPhysicalField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private string parentTaxCodeField;

        private bool isActiveField;

        private bool isSstCertifiedField;

        /// <remarks/>
        public int TaxCodeId
        {
            get
            {
                return this.taxCodeIdField;
            }
            set
            {
                this.taxCodeIdField = value;
            }
        }

        /// <remarks/>
        public string TaxCodeValue
        {
            get
            {
                return this.taxCodeValueField;
            }
            set
            {
                this.taxCodeValueField = value;
            }
        }

        /// <remarks/>
        public string TaxCodeTypeId
        {
            get
            {
                return this.taxCodeTypeIdField;
            }
            set
            {
                this.taxCodeTypeIdField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public bool IsPhysical
        {
            get
            {
                return this.isPhysicalField;
            }
            set
            {
                this.isPhysicalField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public string ParentTaxCode
        {
            get
            {
                return this.parentTaxCodeField;
            }
            set
            {
                this.parentTaxCodeField = value;
            }
        }

        /// <remarks/>
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        public bool IsSstCertified
        {
            get
            {
                return this.isSstCertifiedField;
            }
            set
            {
                this.isSstCertifiedField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "Nexus")]
    [ComVisible(false)]
    public class ProxyNexus
    {

        private int nexusIdField;

        private int companyIdField;

        private string countryField;

        private string stateField;

        private ProxyJurisTypeId jurisTypeIdField;

        private string jurisCodeField;

        private string jurisNameField;

        private string shortNameField;

        private System.DateTime effDateField;

        private System.DateTime endDateField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private ProxyNexusTypeId nexusTypeIdField;

        private int accountingMethodIdField;

        private bool hasLocalNexusField;

        private string sourcingField;

        private ProxyLocalNexusTypeId localNexusTypeIdField;

        private string taxIdField;

        /// <remarks/>
        public int NexusId
        {
            get
            {
                return this.nexusIdField;
            }
            set
            {
                this.nexusIdField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public ProxyJurisTypeId JurisTypeId
        {
            get
            {
                return this.jurisTypeIdField;
            }
            set
            {
                this.jurisTypeIdField = value;
            }
        }

        /// <remarks/>
        public string JurisCode
        {
            get
            {
                return this.jurisCodeField;
            }
            set
            {
                this.jurisCodeField = value;
            }
        }

        /// <remarks/>
        public string JurisName
        {
            get
            {
                return this.jurisNameField;
            }
            set
            {
                this.jurisNameField = value;
            }
        }

        /// <remarks/>
        public string ShortName
        {
            get
            {
                return this.shortNameField;
            }
            set
            {
                this.shortNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EffDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public ProxyNexusTypeId NexusTypeId
        {
            get
            {
                return this.nexusTypeIdField;
            }
            set
            {
                this.nexusTypeIdField = value;
            }
        }

        /// <remarks/>
        public int AccountingMethodId
        {
            get
            {
                return this.accountingMethodIdField;
            }
            set
            {
                this.accountingMethodIdField = value;
            }
        }

        /// <remarks/>
        public bool HasLocalNexus
        {
            get
            {
                return this.hasLocalNexusField;
            }
            set
            {
                this.hasLocalNexusField = value;
            }
        }

        /// <remarks/>
        public string Sourcing
        {
            get
            {
                return this.sourcingField;
            }
            set
            {
                this.sourcingField = value;
            }
        }

        /// <remarks/>
        public string TaxId
        {
            get
            {
                return this.taxIdField;
            }
            set
            {
                this.taxIdField = value;
            }
        }

        /// <remarks/>
        public ProxyLocalNexusTypeId LocalNexusTypeId
        {
            get
            {
                return this.localNexusTypeIdField;
            }
            set
            {
                this.localNexusTypeIdField = value;
            }
        }

        internal void CopyTo(ProxyNexus svcNexus)
        {
            throw new NotImplementedException();
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TypeId")]
    [ComVisible(false)]
    public enum ProxyNexusTypeId
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Volunteer,

        /// <remarks/>
        NonVolunteer,

        /// <remarks/>
        SSTVolunteer,

        /// <remarks/>
        SSTNonVolunteer,

        /// <remarks/>
        Collect,

        /// <remarks/>
        Legal,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "NexusTypeId")]
    [ComVisible(false)]
    public enum ProxyLocalNexusTypeId
    {

        /// <remarks/>
        Selected,

        /// <remarks/>
        StateAdministered,

        /// <remarks/>
        All,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "JurisTypeId")]
    [ComVisible(false)]
    public enum ProxyJurisTypeId
    {

        /// <remarks/>
        STA,

        /// <remarks/>
        CTY,

        /// <remarks/>
        CIT,

        /// <remarks/>
        STJ,

        /// <remarks/>
        CNT,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TaxDependencyLevelId")]
    [ComVisible(false)]
    public enum TaxDependencyLevelId
    {

        /// <remarks/>
        Document,

        /// <remarks/>
        State,

        /// <remarks/>
        TaxRegion,

        /// <remarks/>
        Address,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanyReturn")]
    [ComVisible(false)]
    public class ProxyCompanyReturn
    {

        private int yearStartField;

        private long companyReturnIdField;

        private ProxyCompanySupportingReturn[] companySupportingReturnField;

        private int companyIdField;

        private string companyNameField;

        private string returnNameField;

        private ProxyFilingFrequencyId filingFrequencyIdField;

        private short monthsField;

        private string registrationIdField;

        private string einField;

        private string line1Field;

        private string line2Field;

        private string cityField;

        private string regionField;

        private string postalCodeField;

        private string countryField;

        private string phoneField;

        private string descriptionField;

        private string legalEntityNameField;

        private System.DateTime effDateField;

        private System.DateTime endDateField;

        private int createdUserIdField;

        private System.DateTime createdDateField;

        private int modifiedUserIdField;

        private System.DateTime modifiedDateField;

        private int filingCalendarIdField;

        private ProxyFilingTypeId filingTypeIdField;

        private string efilePasswordField;

        private byte prepayPercentageField;

        private string taxTypeIdField;

        private string noteField;

        private string alSignOnField;

        private string alAccessCodeField;

        private string meBusinessCodeField;

        private string iaBenField;

        private string ctRegField;

        private string other1NameField;

        private string other1ValueField;

        private string other2NameField;

        private string other2ValueField;

        private string other3NameField;

        private string other3ValueField;

        private string locationCodeField;

        private ProxyOutletTypeId outletTypeIdField;

        /// <remarks/>
        public int YearStart
        {
            get
            {
                return this.yearStartField;
            }
            set
            {
                this.yearStartField = value;
            }
        }

        /// <remarks/>
        public long CompanyReturnId
        {
            get
            {
                return this.companyReturnIdField;
            }
            set
            {
                this.companyReturnIdField = value;
            }
        }

        /// <remarks/>
        public ProxyCompanySupportingReturn[] CompanySupportingReturn
        {
            get
            {
                return this.companySupportingReturnField;
            }
            set
            {
                this.companySupportingReturnField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string CompanyName
        {
            get
            {
                return this.companyNameField;
            }
            set
            {
                this.companyNameField = value;
            }
        }

        /// <remarks/>
        public string ReturnName
        {
            get
            {
                return this.returnNameField;
            }
            set
            {
                this.returnNameField = value;
            }
        }

        /// <remarks/>
        public ProxyFilingFrequencyId FilingFrequencyId
        {
            get
            {
                return this.filingFrequencyIdField;
            }
            set
            {
                this.filingFrequencyIdField = value;
            }
        }

        /// <remarks/>
        public short Months
        {
            get
            {
                return this.monthsField;
            }
            set
            {
                this.monthsField = value;
            }
        }

        /// <remarks/>
        public string RegistrationId
        {
            get
            {
                return this.registrationIdField;
            }
            set
            {
                this.registrationIdField = value;
            }
        }

        /// <remarks/>
        public string Ein
        {
            get
            {
                return this.einField;
            }
            set
            {
                this.einField = value;
            }
        }

        /// <remarks/>
        public string Line1
        {
            get
            {
                return this.line1Field;
            }
            set
            {
                this.line1Field = value;
            }
        }

        /// <remarks/>
        public string Line2
        {
            get
            {
                return this.line2Field;
            }
            set
            {
                this.line2Field = value;
            }
        }

        /// <remarks/>
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }

        /// <remarks/>
        public string Region
        {
            get
            {
                return this.regionField;
            }
            set
            {
                this.regionField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public string LegalEntityName
        {
            get
            {
                return this.legalEntityNameField;
            }
            set
            {
                this.legalEntityNameField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EffDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int FilingCalendarId
        {
            get
            {
                return this.filingCalendarIdField;
            }
            set
            {
                this.filingCalendarIdField = value;
            }
        }

        /// <remarks/>
        public ProxyFilingTypeId FilingTypeId
        {
            get
            {
                return this.filingTypeIdField;
            }
            set
            {
                this.filingTypeIdField = value;
            }
        }

        /// <remarks/>
        public string EfilePassword
        {
            get
            {
                return this.efilePasswordField;
            }
            set
            {
                this.efilePasswordField = value;
            }
        }

        /// <remarks/>
        public byte PrepayPercentage
        {
            get
            {
                return this.prepayPercentageField;
            }
            set
            {
                this.prepayPercentageField = value;
            }
        }

        /// <remarks/>
        public string TaxTypeId
        {
            get
            {
                return this.taxTypeIdField;
            }
            set
            {
                this.taxTypeIdField = value;
            }
        }

        /// <remarks/>
        public string Note
        {
            get
            {
                return this.noteField;
            }
            set
            {
                this.noteField = value;
            }
        }

        /// <remarks/>
        public string AlSignOn
        {
            get
            {
                return this.alSignOnField;
            }
            set
            {
                this.alSignOnField = value;
            }
        }

        /// <remarks/>
        public string AlAccessCode
        {
            get
            {
                return this.alAccessCodeField;
            }
            set
            {
                this.alAccessCodeField = value;
            }
        }

        /// <remarks/>
        public string MeBusinessCode
        {
            get
            {
                return this.meBusinessCodeField;
            }
            set
            {
                this.meBusinessCodeField = value;
            }
        }

        /// <remarks/>
        public string IaBen
        {
            get
            {
                return this.iaBenField;
            }
            set
            {
                this.iaBenField = value;
            }
        }

        /// <remarks/>
        public string CtReg
        {
            get
            {
                return this.ctRegField;
            }
            set
            {
                this.ctRegField = value;
            }
        }

        /// <remarks/>
        public string Other1Name
        {
            get
            {
                return this.other1NameField;
            }
            set
            {
                this.other1NameField = value;
            }
        }

        /// <remarks/>
        public string Other1Value
        {
            get
            {
                return this.other1ValueField;
            }
            set
            {
                this.other1ValueField = value;
            }
        }

        /// <remarks/>
        public string Other2Name
        {
            get
            {
                return this.other2NameField;
            }
            set
            {
                this.other2NameField = value;
            }
        }

        /// <remarks/>
        public string Other2Value
        {
            get
            {
                return this.other2ValueField;
            }
            set
            {
                this.other2ValueField = value;
            }
        }

        /// <remarks/>
        public string Other3Name
        {
            get
            {
                return this.other3NameField;
            }
            set
            {
                this.other3NameField = value;
            }
        }

        /// <remarks/>
        public string Other3Value
        {
            get
            {
                return this.other3ValueField;
            }
            set
            {
                this.other3ValueField = value;
            }
        }

        /// <remarks/>
        public string LocationCode
        {
            get
            {
                return this.locationCodeField;
            }
            set
            {
                this.locationCodeField = value;
            }
        }

        /// <remarks/>
        public ProxyOutletTypeId OutletTypeId
        {
            get
            {
                return this.outletTypeIdField;
            }
            set
            {
                this.outletTypeIdField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "FilingFrequencyId")]
    [ComVisible(false)]
    public enum ProxyFilingFrequencyId
    {

        /// <remarks/>
        Monthly,

        /// <remarks/>
        Quarterly,

        /// <remarks/>
        SemiAnnually,

        /// <remarks/>
        Annually,

        /// <remarks/>
        Bimonthly,

        /// <remarks/>
        Occasional,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "FilingTypeId")]
    [ComVisible(false)]
    public enum ProxyFilingTypeId
    {

        /// <remarks/>
        PaperReturn,

        /// <remarks/>
        ElectronicReturn,

        /// <remarks/>
        SER,

        /// <remarks/>
        EFTPaper,

        /// <remarks/>
        PhonePaper,

        /// <remarks/>
        SignatureReady,

        /// <remarks/>
        EfileCheck,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "OutletTypeId")]
    [ComVisible(false)]
    public enum ProxyOutletTypeId
    {

        /// <remarks/>
        None,

        /// <remarks/>
        Schedule,

        /// <remarks/>
        Duplicate,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TaxTypeId")]
    [ComVisible(false)]
    public enum ProxyTaxTypeId
    {

        /// <remarks/>
        B,

        /// <remarks/>
        C,

        /// <remarks/>
        S,

        /// <remarks/>
        U,

        /// <remarks/>
        O,

        /// <remarks/>
        I,

        /// <remarks/>
        N,

        /// <remarks/>
        R,

        /// <remarks/>
        F,

        /// <remarks/>
        E,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TaxRuleTypeId")]
    [ComVisible(false)]
    public enum ProxyTaxRuleTypeId
    {

        /// <remarks/>
        RateRule,

        /// <remarks/>
        RateOverrideRule,

        /// <remarks/>
        BaseRule,

        /// <remarks/>
        ExemptEntityRule,

        /// <remarks/>
        ProductTaxabilityRule,

        /// <remarks/>
        NexusRule,
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "TaxRule")]
    [ComVisible(false)]
    public class ProxyTaxRule
    {

        private int taxRuleIdField;

        private int companyIdField;

        private string stateField;

        private string stateCodeField;

        private string countyCodeField;

        private ProxyJurisTypeId jurisTypeIdField;

        private string jurisCodeField;

        private string jurisNameField;

        private int taxCodeIdField;

        private string customerUsageTypeField;

        private ProxyTaxTypeId taxTypeIdField;

        private ProxyTaxRuleTypeId taxRuleTypeIdField;

        private bool isAllJurisField;

        private decimal valueField;

        private decimal capField;

        private decimal thresholdField;

        private string optionsField;

        private System.DateTime effDateField;

        private System.DateTime endDateField;

        private string descriptionField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private bool isStProField;

        private string rateTypeIdField;

        private ProxyCompany companyField;

        private ProxyTaxCode taxCodeField;

        private string countryField;

        private string sourcingField;

        /// <remarks/>
        public int TaxRuleId
        {
            get
            {
                return this.taxRuleIdField;
            }
            set
            {
                this.taxRuleIdField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }

        /// <remarks/>
        public string StateCode
        {
            get
            {
                return this.stateCodeField;
            }
            set
            {
                this.stateCodeField = value;
            }
        }

        /// <remarks/>
        public string CountyCode
        {
            get
            {
                return this.countyCodeField;
            }
            set
            {
                this.countyCodeField = value;
            }
        }

        /// <remarks/>
        public ProxyJurisTypeId JurisTypeId
        {
            get
            {
                return this.jurisTypeIdField;
            }
            set
            {
                this.jurisTypeIdField = value;
            }
        }

        /// <remarks/>
        public string JurisCode
        {
            get
            {
                return this.jurisCodeField;
            }
            set
            {
                this.jurisCodeField = value;
            }
        }

        /// <remarks/>
        public string JurisName
        {
            get
            {
                return this.jurisNameField;
            }
            set
            {
                this.jurisNameField = value;
            }
        }

        /// <remarks/>
        public int TaxCodeId
        {
            get
            {
                return this.taxCodeIdField;
            }
            set
            {
                this.taxCodeIdField = value;
            }
        }

        /// <remarks/>
        public string CustomerUsageType
        {
            get
            {
                return this.customerUsageTypeField;
            }
            set
            {
                this.customerUsageTypeField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxTypeId TaxTypeId
        {
            get
            {
                return this.taxTypeIdField;
            }
            set
            {
                this.taxTypeIdField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxRuleTypeId TaxRuleTypeId
        {
            get
            {
                return this.taxRuleTypeIdField;
            }
            set
            {
                this.taxRuleTypeIdField = value;
            }
        }

        /// <remarks/>
        public bool IsAllJuris
        {
            get
            {
                return this.isAllJurisField;
            }
            set
            {
                this.isAllJurisField = value;
            }
        }

        /// <remarks/>
        public decimal Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }

        /// <remarks/>
        public decimal Cap
        {
            get
            {
                return this.capField;
            }
            set
            {
                this.capField = value;
            }
        }

        /// <remarks/>
        public decimal Threshold
        {
            get
            {
                return this.thresholdField;
            }
            set
            {
                this.thresholdField = value;
            }
        }

        /// <remarks/>
        public string Options
        {
            get
            {
                return this.optionsField;
            }
            set
            {
                this.optionsField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EffDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public bool IsStPro
        {
            get
            {
                return this.isStProField;
            }
            set
            {
                this.isStProField = value;
            }
        }

        /// <remarks/>
        public string RateTypeId
        {
            get
            {
                return this.rateTypeIdField;
            }
            set
            {
                this.rateTypeIdField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany ProxyCompany
        {
            get
            {
                return this.companyField;
            }
            set
            {
                this.companyField = value;
            }
        }

        /// <remarks/>
        public ProxyTaxCode TaxCode
        {
            get
            {
                return this.taxCodeField;
            }
            set
            {
                this.taxCodeField = value;
            }
        }

        /// <remarks/>
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }

        /// <remarks/>
        public string Sourcing
        {
            get
            {
                return this.sourcingField;
            }
            set
            {
                this.sourcingField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanySupportingReturn")]
    [ComVisible(false)]
    public class ProxyCompanySupportingReturn
    {

        private long companyReturnIdField;

        private int companySupportingReturnIdField;

        private string returnNameField;

        /// <remarks/>
        public long CompanyReturnId
        {
            get
            {
                return this.companyReturnIdField;
            }
            set
            {
                this.companyReturnIdField = value;
            }
        }

        /// <remarks/>
        public int CompanySupportingReturnId
        {
            get
            {
                return this.companySupportingReturnIdField;
            }
            set
            {
                this.companySupportingReturnIdField = value;
            }
        }

        /// <remarks/>
        public string ReturnName
        {
            get
            {
                return this.returnNameField;
            }
            set
            {
                this.returnNameField = value;
            }
        }
    }

    /// <remarks/>
    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "CompanySetting")]
    [ComVisible(false)]
    public class ProxyCompanySetting
    {

        private int companySettingIdField;

        private int companyIdField;

        private string setField;

        private string nameField;

        private string valueField;

        /// <remarks/>
        public int CompanySettingId
        {
            get
            {
                return this.companySettingIdField;
            }
            set
            {
                this.companySettingIdField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }

        /// <remarks/>
        public string Set
        {
            get
            {
                return this.setField;
            }
            set
            {
                this.setField = value;
            }
        }

        /// <remarks/>
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }

        /// <remarks/>
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "NexusFetchResult")]
    [ComVisible(false)]
    public class ProxyNexusFetchResult : ProxyBaseResult
    {

        private ProxyNexus[] nexusesField;

        private int recordCountField;

        /// <remarks/>
        public ProxyNexus[] Nexuses
        {
            get
            {
                return this.nexusesField;
            }
            set
            {
                this.nexusesField = value;
            }
        }

        /// <remarks/>
        public int RecordCount
        {
            get
            {
                return this.recordCountField;
            }
            set
            {
                this.recordCountField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "Account")]
    [ComVisible(false)]
    public class ProxyAccount
    {

        private int accountIdField;

        private int siteIdField;

        private string accountNameField;

        private AccountStatusId accountStatusIdField;

        private System.DateTime effDateField;

        private System.DateTime endDateField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private Avalara.AvaTax.Adapter.AccountService.Service[] servicesField;

        private Site siteField;

        private AddressServiceConfig addressServiceConfigField;

        private FormsServiceConfig formsServiceConfigField;

        private TaxServiceConfig taxServiceConfigField;

        private ProxyCompany[] companiesField;

        private ProxyUser[] usersField;

        /// <remarks/>
        public int AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        public int SiteId
        {
            get
            {
                return this.siteIdField;
            }
            set
            {
                this.siteIdField = value;
            }
        }

        /// <remarks/>
        public string AccountName
        {
            get
            {
                return this.accountNameField;
            }
            set
            {
                this.accountNameField = value;
            }
        }

        /// <remarks/>
        public AccountStatusId AccountStatusId
        {
            get
            {
                return this.accountStatusIdField;
            }
            set
            {
                this.accountStatusIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EffDate
        {
            get
            {
                return this.effDateField;
            }
            set
            {
                this.effDateField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType = "date")]
        public System.DateTime EndDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public Avalara.AvaTax.Adapter.AccountService.Service[] Services
        {
            get
            {
                return this.servicesField;
            }
            set
            {
                this.servicesField = value;
            }
        }

        /// <remarks/>
        public Site Site
        {
            get
            {
                return this.siteField;
            }
            set
            {
                this.siteField = value;
            }
        }

        /// <remarks/>
        public AddressServiceConfig AddressServiceConfig
        {
            get
            {
                return this.addressServiceConfigField;
            }
            set
            {
                this.addressServiceConfigField = value;
            }
        }

        /// <remarks/>
        public FormsServiceConfig FormsServiceConfig
        {
            get
            {
                return this.formsServiceConfigField;
            }
            set
            {
                this.formsServiceConfigField = value;
            }
        }

        /// <remarks/>
        public TaxServiceConfig TaxServiceConfig
        {
            get
            {
                return this.taxServiceConfigField;
            }
            set
            {
                this.taxServiceConfigField = value;
            }
        }

        /// <remarks/>
        public ProxyCompany[] Companies
        {
            get
            {
                return this.companiesField;
            }
            set
            {
                this.companiesField = value;
            }
        }

        /// <remarks/>
        public ProxyUser[] Users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }
    }
         

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "User")]
    [ComVisible(false)]
    public class ProxyUser
    {
        public ProxyUser()
        {

        }
        private int userIdField;

        private int accountIdField;

        private string userNameField;

        private string firstNameField;

        private string lastNameField;

        private string emailField;

        private string postalCodeField;

        private string passwordField;

        private PasswordStatusId passwordStatusIdField;

        private SecurityRoleId securityRoleIdField;

        private bool isActiveField;

        private System.DateTime createdDateField;

        private int createdUserIdField;

        private System.DateTime modifiedDateField;

        private int modifiedUserIdField;

        private int failedLoginAttemptsField;

        private ProxyAccount accountField;

        private SecurityRole[] securityRolesField;

        private Permission[] permissionsField;

        private int companyIdField;

        /// <remarks/>
        public int UserId
        {
            get
            {
                return this.userIdField;
            }
            set
            {
                this.userIdField = value;
            }
        }

        /// <remarks/>
        public int AccountId
        {
            get
            {
                return this.accountIdField;
            }
            set
            {
                this.accountIdField = value;
            }
        }

        /// <remarks/>
        public string UserName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }

        /// <remarks/>
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }

        /// <remarks/>
        public string LastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }

        /// <remarks/>
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }

        /// <remarks/>
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }

        /// <remarks/>
        public string Password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }

        /// <remarks/>
        public PasswordStatusId PasswordStatusId
        {
            get
            {
                return this.passwordStatusIdField;
            }
            set
            {
                this.passwordStatusIdField = value;
            }
        }

        /// <remarks/>
        public SecurityRoleId SecurityRoleId
        {
            get
            {
                return this.securityRoleIdField;
            }
            set
            {
                this.securityRoleIdField = value;
            }
        }

        /// <remarks/>
        public bool IsActive
        {
            get
            {
                return this.isActiveField;
            }
            set
            {
                this.isActiveField = value;
            }
        }

        /// <remarks/>
        public System.DateTime CreatedDate
        {
            get
            {
                return this.createdDateField;
            }
            set
            {
                this.createdDateField = value;
            }
        }

        /// <remarks/>
        public int CreatedUserId
        {
            get
            {
                return this.createdUserIdField;
            }
            set
            {
                this.createdUserIdField = value;
            }
        }

        /// <remarks/>
        public System.DateTime ModifiedDate
        {
            get
            {
                return this.modifiedDateField;
            }
            set
            {
                this.modifiedDateField = value;
            }
        }

        /// <remarks/>
        public int ModifiedUserId
        {
            get
            {
                return this.modifiedUserIdField;
            }
            set
            {
                this.modifiedUserIdField = value;
            }
        }

        /// <remarks/>
        public int FailedLoginAttempts
        {
            get
            {
                return this.failedLoginAttemptsField;
            }
            set
            {
                this.failedLoginAttemptsField = value;
            }
        }

        /// <remarks/>
        public ProxyAccount Account
        {
            get
            {
                return this.accountField;
            }
            set
            {
                this.accountField = value;
            }
        }

        /// <remarks/>
        public SecurityRole[] SecurityRoles
        {
            get
            {
                return this.securityRolesField;
            }
            set
            {
                this.securityRolesField = value;
            }
        }

        /// <remarks/>
        public Permission[] Permissions
        {
            get
            {
                return this.permissionsField;
            }
            set
            {
                this.permissionsField = value;
            }
        }

        /// <remarks/>
        public int CompanyId
        {
            get
            {
                return this.companyIdField;
            }
            set
            {
                this.companyIdField = value;
            }
        }
    }

    /// <remarks/>
    [XmlType(Namespace = "http://avatax.avalara.com/services", TypeName = "UserFetchResult")]
    [ComVisible(false)]
    public class ProxyUserFetchResult : ProxyBaseResult
    {

        private ProxyUser[] usersField;

        private int recordCountField;

        /// <remarks/>
        public ProxyUser[] Users
        {
            get
            {
                return this.usersField;
            }
            set
            {
                this.usersField = value;
            }
        }

        /// <remarks/>
        public int RecordCount
        {
            get
            {
                return this.recordCountField;
            }
            set
            {
                this.recordCountField = value;
            }
        }
    }

}